# Домашнее задание к лекции "Функции"

Вам нужно помочь секретарю автоматизировать работу. Для этого нужно написать программу, которая будет на основе хранимых данных исполнять пользовательские команды.

Исходные данные имеют следующую структуру:

1. перечень всех документов
```
documents = [
    {'type': 'passport', 'number': '2207 876234', 'name': 'Василий Гупкин'},
    {'type': 'invoice', 'number': '11-2', 'name': 'Геннадий Покемонов'},
    {'type': 'insurance', 'number': '10006', 'name': 'Аристарх Павлов'}
]
```
2. перечень полок, на которых хранятся документы (если документ есть в documents, то он обязательно должен быть и в directories)
```
directories = {
    '1': ['2207 876234', '11-2'],
    '2': ['10006'],
    '3': []
}
```

Общие требования к программе:
- код должен быть грамотно декомпозирован (каждая функция отвечает за свою конкретную задачу, дублирующийся функционал переиспользуется, а его код не повторяется);
- в коде отсутствуют глобальные переменные (за исключением **documents** и **directories**);
- пользовательский ввод обрабатывается в цикле **while** до тех пор, пока пользователь явно не завершит программу (вводом команды "**q**").

## Задание 1

### Пункт 1. Пользователь по команде "*p*" может узнать владельца документа по его номеру

Примеры работы:

1.

```
Введите команду:
p

Введите номер документа:
10006
```
Результат:  
`Владелец документа: Аристарх Павлов`

2.
```
Введите команду:
p

Введите номер документа:
12345
```
Результат:  
`Документ не найден в базе`

### Пункт 2. Пользователь по команде "*s*" может по номеру документа узнать на какой полке он хранится

Примеры работы:

1.

```
Введите команду:
s

Введите номер документа:
10006
```
Результат:  
`Документ хранится на полке: 2`

2.
```
Введите команду:
p

Введите номер документа:
12345
```
Результат:  
`Документ не найден в базе`

### Пункт 3. Пользователь по команде "*l*" может увидеть полную информацию по всем документам

Пример работы:

```
Введите команду:
l
```

Результат:  
```
№: 2207 876234, тип: passport, владелец: Василий Гупкин, полка хранения: 1
№: 11-2, тип: invoice, владелец: Геннадий Покемонов, полка хранения: 1
№: 10006, тип: insurance, владелец: Аристарх Павлов, полка хранения: 2
```

### Пункт 4. Пользователь по команде "*ads*" может добавить новую полку

Примеры работы:

1.

```
Введите команду:
ads

Введите номер полки:
10
```
Результат:  
`Полка добавлена. Текущий перечень полок: 1, 2, 3, 10.`

2.
```
Введите команду:
ads

Введите номер полки:
1
```
Результат:  
`Такая полка уже существует. Текущий перечень полок: 1, 2, 3.`

### Пункт 5. Пользователь по команде "*ds*" может удалить существующую полку из данных (только если она пустая)

Примеры работы:

1.

```
Введите команду:
ds

Введите номер полки:
3
```
Результат:  
`Полка удалена. Текущий перечень полок: 1, 2.`

2.
```
Введите команду:
ds

Введите номер полки:
1
```
Результат:  
`На полке есть документа, удалите их перед удалением полки. Текущий перечень полок: 1, 2, 3.`

3.
```
Введите команду:
ds

Введите номер полки:
4
```
Результат:  
`Такой полки не существует. Текущий перечень полок: 1, 2, 3.`

## Решение 1

In [2]:
import sys
documents = [
 {'type': 'passport', 'number': '2207 876234', 'name': 'Василий Гупкин'},
 {'type': 'invoice', 'number': '11-2', 'name': 'Геннадий Покемонов'},
 {'type': 'insurance', 'number': '10006', 'name': 'Аристарх Павлов'}
]

directories = {
 '1': ['2207 876234', '11-2'],
 '2': ['10006'],
 '3': []
}


class App(object):
    def __new__(cls):
        if not hasattr(cls, 'instance'):
            cls.instance = super(App, cls).__new__(cls)
        return cls.instance
    
def cmd_wrong():
    print('Некорректная команда.')

# Пользователь по команде "p" может узнать владельца документа по его номеру
def cmd_p():
    doc_num = input('Введите номер документа:')
    try:
        print('Владелец документа: {name:s}'.format(name=App().docs[doc_num]['name']))
    except KeyError:
        print('Документ не найден в базе')
    
# Пользователь по команде "s" может по номеру документа узнать на какой полке он хранится
def cmd_s():
    doc_num = input('Введите номер документа:')
    try:
        print('Документ хранится на полке: {dir:s}'.format(dir=App().docs[doc_num]['dir']))
    except KeyError:
        print('Документ не найден в базе')

# Пользователь по команде "l" может увидеть полную информацию по всем документам
def cmd_l():
    print('Текущий список документов:',
          *['№: {num:s}, тип: {type:s}, владелец: {name:s}, полка хранения: {dir:s}'.
           format(num=k, type=v['type'], name=v['name'], dir=v['dir']) 
           for k, v in App().docs.items()], sep='\n')

# Пользователь по команде "ads" может добавить новую полку
def cmd_ads():
    dir_num = input('Введите номер полки:')
    if dir_num in App().dirs:
        print('Такая полка уже существует. Текущий перечень полок: {dirs:s}'.
              format(dirs=', '.join(App().dirs)))
    else:
        App().dirs.add(dir_num)
        print('Полка добавлена. Текущий перечень полок: {dirs:s}'.
              format(dirs=', '.join(App().dirs)))

# Пользователь по команде "ds" может удалить существующую полку из данных (только если она пустая)
def cmd_ds():
    dir_num = input('Введите номер полки:')
    docs = [k for k, v in App().docs.items() if v['dir'] == dir_num]
    if docs:
        print('На полке есть документы: {docs:s}, удалите их перед удалением полки. Текущий перечень полок: {dirs:s}'.
              format(docs=str(docs), dirs=', '.join(App().dirs)))
    else:
        App().dirs.remove(dir_num)
        print('Полка удалена. Текущий перечень полок: {dirs:s}'.
              format(docs=str(docs), dirs=', '.join(App().dirs)))

# Пользователь по команде "ad" может добавить новый документ в данные
def cmd_ad():
    doc_num = input('Введите номер документа:')
    doc_type = input('Введите тип документа:')
    doc_name = input('Введите владельца документа:')
    doc_dir = input('Введите полку для хранения:')
    if doc_num in App().docs.keys():
        print('Документ с номером {doc_num:s} уже существует.'.format(doc_num=doc_num))
        cmd_l()
    elif doc_dir not in App().dirs:
        print('Такой полки не существует. Добавьте полку командой ads.')
        cmd_l()
    else:
        App().docs[doc_num] = {'type': doc_type, 'name': doc_name, 'dir': doc_dir}
        print('Документ добавлен.')
        cmd_l()

# Пользователь по команде "d" может удалить документ из данных
def cmd_d():
    doc_num = input('Введите номер документа:')
    try:
        App().docs.pop(doc_num)            
        print('Документ удален.')
        #cmd_l()
    except KeyError:
        print('Документ не найден в базе.')
    finally:            
        cmd_l()

# Пользователь по команде "m" может переместить документ с полки на полку
def cmd_m():
    doc_num = input('Введите номер документа:')
    dir_num = input('Введите номер полки:')
    if dir_num in App().dirs:
        try:
            App().docs[doc_num]['dir'] = dir_num
            print('Документ перемещен.')
        except KeyError:
            print('Документ не найден в базе.')
        finally:            
            cmd_l()
    else:
        print('Такой полки не существует. Добавьте полку командой ads.')                       

# Все фигня, давай по новой
def cmd_q():
    sys.exit(0) # Jupyter умеет гасить SystemExit? Без обходных путей
       
App().docs = {d['number']: {'type': d['type'], 'name': d['name'],
                            'dir': [k for k, v in directories.items() if d['number'] in v][0]} 
              for d in documents}
App().dirs = set(directories.keys())

while True:
    {
        'p': cmd_p,
        's': cmd_s,
        'l': cmd_l,
        'ads': cmd_ads,
        'ds': cmd_ds,
        'q': cmd_q,
        'ad': cmd_ad,
        'd': cmd_d,
        'm': cmd_m
    }.get(input('Введите команду:'), cmd_wrong)()


Введите команду:l
Текущий список документов:
№: 2207 876234, тип: passport, владелец: Василий Гупкин, полка хранения: 1
№: 11-2, тип: invoice, владелец: Геннадий Покемонов, полка хранения: 1
№: 10006, тип: insurance, владелец: Аристарх Павлов, полка хранения: 2
Введите команду:d
Введите номер документа:10007
Документ не найден в базе.
Текущий список документов:
№: 2207 876234, тип: passport, владелец: Василий Гупкин, полка хранения: 1
№: 11-2, тип: invoice, владелец: Геннадий Покемонов, полка хранения: 1
№: 10006, тип: insurance, владелец: Аристарх Павлов, полка хранения: 2
Введите команду:d
Введите номер документа:10006
Документ удален.
Текущий список документов:
№: 2207 876234, тип: passport, владелец: Василий Гупкин, полка хранения: 1
№: 11-2, тип: invoice, владелец: Геннадий Покемонов, полка хранения: 1
Введите команду:q


SystemExit: 0

C:\apps\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3426: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.
  warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)


In [1]:
print('fg')

fg


## Задание 2 (необязательное)

Вам необходимо дополнить программу из задания 1 более продвинутыми командами.

### Пункт 1. Пользователь по команде "*ad*" может добавить новый документ в данные

Примеры работы:

1.

```
Введите команду:
ad

Введите номер документа:
42
Введите тип документа:
multipassport
Введите владельца документа:
R2D2
Введите полку для хранения:
3
```
Результат:  
```
Документ добавлен. Текущий список документов:
№: 2207 876234, тип: passport, владелец: Василий Гупкин, полка хранения: 1
№: 11-2, тип: invoice, владелец: Геннадий Покемонов, полка хранения: 1
№: 10006, тип: insurance, владелец: Аристарх Павлов, полка хранения: 2
№: 42, тип: multipassport, владелец: R2D2, полка хранения: 3
```

2.
```
Введите команду:
ad

Введите номер документа:
42
Введите тип документа:
multipassport
Введите владельца документа:
R2D2
Введите полку для хранения:
4
```
Результат:  
```
Такой полки не существует. Добавьте полку командой as. 
Текущий список документов:
№: 2207 876234, тип: passport, владелец: Василий Гупкин, полка хранения: 1
№: 11-2, тип: invoice, владелец: Геннадий Покемонов, полка хранения: 1
№: 10006, тип: insurance, владелец: Аристарх Павлов, полка хранения: 2
```

### Пункт 2. Пользователь по команде "*d*" может удалить документ из данных

Примеры работы:

1.

```
Введите команду:
d

Введите номер документа:
10006
```
Результат:  
```
Документ удален. 
Текущий список документов:
№: 2207 876234, тип: passport, владелец: Василий Гупкин, полка хранения: 1
№: 11-2, тип: invoice, владелец: Геннадий Покемонов, полка хранения: 1
```

2.
```
Введите команду:
d

Введите номер документа:
123456
```
Результат:  
```
Документ не найден в базе. 
Текущий список документов:
№: 2207 876234, тип: passport, владелец: Василий Гупкин, полка хранения: 1
№: 11-2, тип: invoice, владелец: Геннадий Покемонов, полка хранения: 1
№: 10006, тип: insurance, владелец: Аристарх Павлов, полка хранения: 2
```

### Пункт 3. Пользователь по команде "*m*" может переместить документ с полки на полку

Примеры работы:

1.

```
Введите команду:
m

Введите номер документа:
11-2
Введите номер полки:
3
```
Результат:  
```
Документ перемещен. 
Текущий список документов:
№: 2207 876234, тип: passport, владелец: Василий Гупкин, полка хранения: 1
№: 11-2, тип: invoice, владелец: Геннадий Покемонов, полка хранения: 3
№: 10006, тип: insurance, владелец: Аристарх Павлов, полка хранения: 2
```

2.
```
Введите команду:
m

Введите номер документа:
11-2
Введите номер полки:
10
```
Результат:  
`Такой полки не существует. Текущий перечень полок: 1, 2, 3.`

3.
```
Введите команду:
m

Введите номер документа:
42
Введите номер полки:
2
```
Результат:  
```
Документ не найден в базе. 
Текущий список документов:
№: 2207 876234, тип: passport, владелец: Василий Гупкин, полка хранения: 1
№: 11-2, тип: invoice, владелец: Геннадий Покемонов, полка хранения: 1
№: 10006, тип: insurance, владелец: Аристарх Павлов, полка хранения: 2
```

#### ПРИМЕЧАНИЕ
Домашнее задание сдается ссылкой на репозиторий [GitHub](https://github.com/).
Не сможем проверить или помочь, если вы пришлете:
- файлы;
- архивы;
- скриншоты кода.

Все обсуждения и консультации по выполнению домашнего задания ведутся только на соответствующем канале в slack.

##### Как правильно задавать вопросы аспирантам, преподавателям и коллегам
Прежде чем задать вопрос, попробуйте найти ответ в интернете. Навык самостоятельного поиска информации — один из важнейших. Каждый практикующий специалист любого уровня делает это ежедневно.

Сформулируйте вопрос по алгоритму:  
1) Что я делаю?  
2) Какого результата я ожидаю?  
3) Как фактический результат отличается от ожидаемого?  
4) Что я уже попробовал сделать, чтобы исправить проблему?  

По возможности прикрепите к вопросу скриншоты либо ссылки на код. Не выкладывайте все решение, оставляйте только проблемный и воспроизводимый участок кода.

In [ ]:
import sys
documents = [
 {'type': 'passport', 'number': '2207 876234', 'name': 'Василий Гупкин'},
 {'type': 'invoice', 'number': '11-2', 'name': 'Геннадий Покемонов'},
 {'type': 'insurance', 'number': '10006', 'name': 'Аристарх Павлов'},
 {'type': 'contract', 'number': '10006', 'name': 'Пеппа Барашева'}
]

directories = {
 '1': ['2207 876234', '11-2'],
 '2': ['10006'],
 '3': ['10006']
}

def cmd_wrong():
    print('Некорректная команда.')

# Пользователь по команде "p" может узнать владельца документа по его номеру
def cmd_p():
    doc_num = input('Введите номер документа:')
    fmt = 'Владелец документа: {dir:s}'
    res = ',\n'.join([fmt.format(dir=d['name']) for d in documents if d['number'] == doc_num])
    print(res if res else 'Документ не найден в базе')

# Пользователь по команде "s" может по номеру документа узнать на какой полке он хранится
def cmd_s():
    doc_num = input('Введите номер документа:')
    fmt = 'Документ хранится на полке: {dir:s}'
    res = ',\n'.join([fmt.format(dir=k) for k, v in directories.items() if doc_num in v])
    print(res if res else 'Документ не найден в базе')

# Пользователь по команде "l" может увидеть полную информацию по всем документам
def cmd_l():
    fmt = '№: {num:d}, тип: {type:s}, владелец: {name:s}, полка хранения: {dir:s}'
    res = ',\n'.join([fmt.format(num=d['number'], type=d['type'], name=d['name'],
                                 dir=', '.join([k for k, v in directories.items() if d['number'] in v]))
                      for d in documents])
    print(res if res else 'Документы не найдены в базе')

# Пользователь по команде "ads" может добавить новую полку
def cmd_ads():
    dir_num = input('Введите номер полки:')
    if dir_num in directories.keys():
        print('Такая полка уже существует. Текущий перечень полок: ' + 
              ', '.join(directories.keys()))
    else:
        directories[dir_num] = []
        print('Полка добавлена. Текущий перечень полок: ' + 
              ', '.join(directories.keys()))

# Пользователь по команде "ds" может удалить существующую полку из данных (только если она пустая)
def cmd_ds():
    dir_num = input('Введите номер полки:')
    if dir_num in directories.keys():
        if not directories[dir_num]:
            del directories[dir_num]
            print('Полка удалена. Текущий перечень полок: ' + 
                  ', '.join(directories.keys()))
        else:
            print('На полке есть документы, удалите их перед удалением полки.' +
                  'Текущий перечень полок: ' + ', '.join(directories.keys()))
    else:
        print('Такой полки не существует. Текущий перечень полок: ' + 
              ', '.join(directories.keys()))

# Все фигня, давай по новой
def cmd_q():
    sys.exit(0) # а Jupyter умеет гасить SystemExit? Без обходных путей

while True:
    {
        'p': cmd_p,
        's': cmd_s,
        'l': cmd_l,
        'ads': cmd_ads,
        'ds': cmd_ds,
        'q': cmd_q
    }.get(input('Введите команду:'), cmd_wrong)()